server:
  port: 8443
  ssl:
    key-alias: guxiangfly.cn
    key-store-type: JKS
    key-store: classpath:guxiangfly.cn.jks
    key-store-password: 45lgrs8gokejt0
security:
  require-ssl: true

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/runningcoin
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver