server:
  port: 443
  ssl:
    key-alias: guxiangfly.cn
    key-store-type: JKS
    key-store: classpath:guxiangfly.cn.jks
    key-store-password: 45lgrs8gokejt0


spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/runningcoin
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver